Added CVE-2020-14181
0x48piraj/jiraffe pull request #10
Opened 2021-02-17 16:04 UTC by Rival420

updated __main__.py and exploits.py as well as the readme.md file

2021-02-18 02:45 UTC, SuperSandro2000 commented on README.md
> +| CVE-2020-14181 | LOW | ffected versions of Atlassian Jira Server and Data Center allow an unauthenticated user to enumerate users via an Information Disclosure vulnerability in the /ViewUserHover.j
```suggestion
| CVE-2020-14181 | LOW | Affected versions of Atlassian Jira Server and Data Center allow an unauthenticated user to enumerate users via an Information Disclosure vulnerability in the /ViewUserHover.jspa endpoint. | Jira < 7.13.16 && 8.0.0 < JIRA < 8.5.7 && 8.6.0 < JIRA < 8.12.0 | |
```

2021-05-01 09:14 UTC, 0x48piraj commented on README.md
> +| CVE-2020-14181 | LOW | ffected versions of Atlassian Jira Server and Data Center allow an unauthenticated user to enumerate users via an Information Disclosure vulnerability in the /ViewUserHover.j
Thanks @SuperSandro2000

2023-01-25 22:15 UTC, 0x48piraj approved these changes

2026-01-04 14:44 UTC, 0x48piraj requested changes
Apologies for the late response. The project architecture has changed since this PR was opened, and this implementation no longer aligns with the current scope. For that reason, I’m closing this PR.

Thanks for the contribution, and feel free to open a new PR that fits the current design.

2026-01-04 14:45 UTC, closed without merging